jQuery(document).ready(function($){
        $('#pointer').tooltip();
        $('#pen').tooltip();
        $('#eraser').tooltip();
        $('#prePage').tooltip();
        $('#nextPage').tooltip();
        $('#scaleUp').tooltip();
        $('#scaleDown').tooltip();
        $('.favor-close-sidebar').tooltip();
        $('.userFile-close-sidebar').tooltip();
        $('.user-close-sidebar').tooltip();
        $('.file-close-sidebar').tooltip();
        $('.close-sidebar').tooltip();
});