package com.haijiao.persist;
// Generated 2013-1-31 15:56:05 by Hibernate Tools 3.2.1.GA



/**
 * StudentfileId generated by hbm2java
 */
public class StudentfileId  implements java.io.Serializable {


     private String fileName;
     private int studentId;

    public StudentfileId() {
    }

    public StudentfileId(String fileName, int studentId) {
       this.fileName = fileName;
       this.studentId = studentId;
    }
   
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudentfileId) ) return false;
		 StudentfileId castOther = ( StudentfileId ) other; 
         
		 return ( (this.getFileName()==castOther.getFileName()) || ( this.getFileName()!=null && castOther.getFileName()!=null && this.getFileName().equals(castOther.getFileName()) ) )
 && (this.getStudentId()==castOther.getStudentId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFileName() == null ? 0 : this.getFileName().hashCode() );
         result = 37 * result + this.getStudentId();
         return result;
   }   


}


