package com.haijiao.persist;
// Generated 2013-1-31 15:56:05 by Hibernate Tools 3.2.1.GA



/**
 * Studentfileindex generated by hbm2java
 */
public class Studentfileindex  implements java.io.Serializable {


     private StudentfileindexId id;
     private Studentfile studentfile;
     private String indexName;

    public Studentfileindex() {
    }

	
    public Studentfileindex(StudentfileindexId id, Studentfile studentfile) {
        this.id = id;
        this.studentfile = studentfile;
    }
    public Studentfileindex(StudentfileindexId id, Studentfile studentfile, String indexName) {
       this.id = id;
       this.studentfile = studentfile;
       this.indexName = indexName;
    }
   
    public StudentfileindexId getId() {
        return this.id;
    }
    
    public void setId(StudentfileindexId id) {
        this.id = id;
    }
    public Studentfile getStudentfile() {
        return this.studentfile;
    }
    
    public void setStudentfile(Studentfile studentfile) {
        this.studentfile = studentfile;
    }
    public String getIndexName() {
        return this.indexName;
    }
    
    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }




}


