package com.haijiao.persist;
// Generated 2013-1-31 15:56:05 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private Integer userId;
     private String password;
     private int grade;
     private String account;
     private Set<Studentfile> studentfiles = new HashSet<Studentfile>(0);

    public Student() {
    }

	
    public Student(String password, int grade, String account) {
        this.password = password;
        this.grade = grade;
        this.account = account;
    }
    public Student(String password, int grade, String account, Set<Studentfile> studentfiles) {
       this.password = password;
       this.grade = grade;
       this.account = account;
       this.studentfiles = studentfiles;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getGrade() {
        return this.grade;
    }
    
    public void setGrade(int grade) {
        this.grade = grade;
    }
    public String getAccount() {
        return this.account;
    }
    
    public void setAccount(String account) {
        this.account = account;
    }
    public Set<Studentfile> getStudentfiles() {
        return this.studentfiles;
    }
    
    public void setStudentfiles(Set<Studentfile> studentfiles) {
        this.studentfiles = studentfiles;
    }




}


