package com.haijiao.persist;
// Generated 2013-1-31 15:56:05 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Studentfile generated by hbm2java
 */
public class Studentfile  implements java.io.Serializable {


     private StudentfileId id;
     private Student student;
     private Set<Studentfileindex> studentfileindexes = new HashSet<Studentfileindex>(0);

    public Studentfile() {
    }

	
    public Studentfile(StudentfileId id, Student student) {
        this.id = id;
        this.student = student;
    }
    public Studentfile(StudentfileId id, Student student, Set<Studentfileindex> studentfileindexes) {
       this.id = id;
       this.student = student;
       this.studentfileindexes = studentfileindexes;
    }
   
    public StudentfileId getId() {
        return this.id;
    }
    
    public void setId(StudentfileId id) {
        this.id = id;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Set<Studentfileindex> getStudentfileindexes() {
        return this.studentfileindexes;
    }
    
    public void setStudentfileindexes(Set<Studentfileindex> studentfileindexes) {
        this.studentfileindexes = studentfileindexes;
    }




}


