package com.haijiao.persist;
// Generated 2013-1-31 15:56:05 by Hibernate Tools 3.2.1.GA



/**
 * StudentfileindexId generated by hbm2java
 */
public class StudentfileindexId  implements java.io.Serializable {


     private String page;
     private int studentId;
     private String fileName;

    public StudentfileindexId() {
    }

    public StudentfileindexId(String page, int studentId, String fileName) {
       this.page = page;
       this.studentId = studentId;
       this.fileName = fileName;
    }
   
    public String getPage() {
        return this.page;
    }
    
    public void setPage(String page) {
        this.page = page;
    }
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudentfileindexId) ) return false;
		 StudentfileindexId castOther = ( StudentfileindexId ) other; 
         
		 return ( (this.getPage()==castOther.getPage()) || ( this.getPage()!=null && castOther.getPage()!=null && this.getPage().equals(castOther.getPage()) ) )
 && (this.getStudentId()==castOther.getStudentId())
 && ( (this.getFileName()==castOther.getFileName()) || ( this.getFileName()!=null && castOther.getFileName()!=null && this.getFileName().equals(castOther.getFileName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPage() == null ? 0 : this.getPage().hashCode() );
         result = 37 * result + this.getStudentId();
         result = 37 * result + ( getFileName() == null ? 0 : this.getFileName().hashCode() );
         return result;
   }   


}


