package com.haijiao.persist;
// Generated 2013-1-31 15:56:05 by Hibernate Tools 3.2.1.GA



/**
 * TeacherfileId generated by hbm2java
 */
public class TeacherfileId  implements java.io.Serializable {


     private int teacherId;
     private String fileName;

    public TeacherfileId() {
    }

    public TeacherfileId(int teacherId, String fileName) {
       this.teacherId = teacherId;
       this.fileName = fileName;
    }
   
    public int getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(int teacherId) {
        this.teacherId = teacherId;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TeacherfileId) ) return false;
		 TeacherfileId castOther = ( TeacherfileId ) other; 
         
		 return (this.getTeacherId()==castOther.getTeacherId())
 && ( (this.getFileName()==castOther.getFileName()) || ( this.getFileName()!=null && castOther.getFileName()!=null && this.getFileName().equals(castOther.getFileName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTeacherId();
         result = 37 * result + ( getFileName() == null ? 0 : this.getFileName().hashCode() );
         return result;
   }   


}


