package com.haijiao.persist;
// Generated 2013-1-31 15:56:05 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Teacher generated by hbm2java
 */
public class Teacher  implements java.io.Serializable {


     private Integer userId;
     private String password;
     private String intro;
     private String account;
     private Set<Teacherfile> teacherfiles = new HashSet<Teacherfile>(0);

    public Teacher() {
    }

	
    public Teacher(String password, String account) {
        this.password = password;
        this.account = account;
    }
    public Teacher(String password, String intro, String account, Set<Teacherfile> teacherfiles) {
       this.password = password;
       this.intro = intro;
       this.account = account;
       this.teacherfiles = teacherfiles;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getIntro() {
        return this.intro;
    }
    
    public void setIntro(String intro) {
        this.intro = intro;
    }
    public String getAccount() {
        return this.account;
    }
    
    public void setAccount(String account) {
        this.account = account;
    }
    public Set<Teacherfile> getTeacherfiles() {
        return this.teacherfiles;
    }
    
    public void setTeacherfiles(Set<Teacherfile> teacherfiles) {
        this.teacherfiles = teacherfiles;
    }




}


