package com.haijiao.persist;
// Generated 2013-1-31 15:56:05 by Hibernate Tools 3.2.1.GA



/**
 * Teacherfileindex generated by hbm2java
 */
public class Teacherfileindex  implements java.io.Serializable {


     private TeacherfileindexId id;
     private Teacherfile teacherfile;
     private String indexName;

    public Teacherfileindex() {
    }

	
    public Teacherfileindex(TeacherfileindexId id, Teacherfile teacherfile) {
        this.id = id;
        this.teacherfile = teacherfile;
    }
    public Teacherfileindex(TeacherfileindexId id, Teacherfile teacherfile, String indexName) {
       this.id = id;
       this.teacherfile = teacherfile;
       this.indexName = indexName;
    }
   
    public TeacherfileindexId getId() {
        return this.id;
    }
    
    public void setId(TeacherfileindexId id) {
        this.id = id;
    }
    public Teacherfile getTeacherfile() {
        return this.teacherfile;
    }
    
    public void setTeacherfile(Teacherfile teacherfile) {
        this.teacherfile = teacherfile;
    }
    public String getIndexName() {
        return this.indexName;
    }
    
    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }




}


