package com.haijiao.persist;
// Generated 2013-1-31 15:56:05 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Teacherfile generated by hbm2java
 */
public class Teacherfile  implements java.io.Serializable {


     private TeacherfileId id;
     private Teacher teacher;
     private Set<Teacherfileindex> teacherfileindexes = new HashSet<Teacherfileindex>(0);

    public Teacherfile() {
    }

	
    public Teacherfile(TeacherfileId id, Teacher teacher) {
        this.id = id;
        this.teacher = teacher;
    }
    public Teacherfile(TeacherfileId id, Teacher teacher, Set<Teacherfileindex> teacherfileindexes) {
       this.id = id;
       this.teacher = teacher;
       this.teacherfileindexes = teacherfileindexes;
    }
   
    public TeacherfileId getId() {
        return this.id;
    }
    
    public void setId(TeacherfileId id) {
        this.id = id;
    }
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
    public Set<Teacherfileindex> getTeacherfileindexes() {
        return this.teacherfileindexes;
    }
    
    public void setTeacherfileindexes(Set<Teacherfileindex> teacherfileindexes) {
        this.teacherfileindexes = teacherfileindexes;
    }




}


