package com.haijiao.persist;
// Generated 2013-1-31 15:56:05 by Hibernate Tools 3.2.1.GA



/**
 * TeacherfileindexId generated by hbm2java
 */
public class TeacherfileindexId  implements java.io.Serializable {


     private String fileName;
     private int teacherId;
     private String page;

    public TeacherfileindexId() {
    }

    public TeacherfileindexId(String fileName, int teacherId, String page) {
       this.fileName = fileName;
       this.teacherId = teacherId;
       this.page = page;
    }
   
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public int getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(int teacherId) {
        this.teacherId = teacherId;
    }
    public String getPage() {
        return this.page;
    }
    
    public void setPage(String page) {
        this.page = page;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TeacherfileindexId) ) return false;
		 TeacherfileindexId castOther = ( TeacherfileindexId ) other; 
         
		 return ( (this.getFileName()==castOther.getFileName()) || ( this.getFileName()!=null && castOther.getFileName()!=null && this.getFileName().equals(castOther.getFileName()) ) )
 && (this.getTeacherId()==castOther.getTeacherId())
 && ( (this.getPage()==castOther.getPage()) || ( this.getPage()!=null && castOther.getPage()!=null && this.getPage().equals(castOther.getPage()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFileName() == null ? 0 : this.getFileName().hashCode() );
         result = 37 * result + this.getTeacherId();
         result = 37 * result + ( getPage() == null ? 0 : this.getPage().hashCode() );
         return result;
   }   


}


